name: "Build ImmortalWrt Installer ISO"

on:
 workflow_dispatch:

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Get Date"
        run: |
          echo "DATESTAMP=$(date +'%Y-%m-%d')" >> $GITHUB_ENV 

      - name: "Checking out git repository"
        uses: actions/checkout@v2

      - name: "Build Image"
        run: |
          ./immortalwrt.sh
      
      - name: "Publish"
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: "ImmortalWrt-Installer-x86_64-ISO"
          body_path: ${{ github.workspace }}/supportFiles/immortalwrt/info.md
          files: |
            output/immortalwrt-installer-x86_64.iso
